/**************** Generator of a character string. ***************
 ** Source Code:	Gets.c					**
 ** Author:		Gustavo Islas Gálvez.			**
 ** Creation Date:	Saturday, December 30, 2023.		**
 ** Purpose:		This program attempts to replace the	**
 **			old C function 'gets' with a custom	**
 **			prototype that takes as arguments the	**
 **			maximum number of characters to store	**
 **			in a character pointer and limits the	**
 **			string input until a specific output	**
 **			character is pressed.			**
*****************************************************************/
//C Standard Libraries.
#include <stdio.h>
#include <stdlib.h>

//Work Symbolic Constants.
#define V_ZERO			0
#define V_ONE			1

//Symbolic Character Constants.
#define CARRIAGE_RETURN		'\n'
#define NULL_CHARACTER		'\0'

/*****************************************************************
 ** Function:		char *gets (size_t *const		**
 **					ptr_szt_idx_chars,	**
 **				const size_t szt_num_chars,	**
 **				const char chr_exit_char).	**
 ** Explanation:	In this function, a contiguous memory	**
 **			area is allocated for the character	**
 **			string and the length given by		**
 **			'szt_num_chars' plus the unit is	**
 **			calculated, through a loop that is	**
 **			responsible for obtaining the captured	**
 **			character and subsequently validating	**
 **			that it is different from a character	**
 **			output provided as an argument to the	**
 **			function.				**
 **			In this function, the array notation is	**
 **			used for the dynamically created pointer**
 **			and the notation itself is used for the	**
 **			given pointer.				**
 **			At the end of the character string,	**
 **			at position 'szt_num_chars' a null	**
 **			character is placed or added.		**
 ** Input Parms:	size_t *const ptr_szt_idx_chars,	**
 **			const size_t szt_num_chars,		**
 **			const char chr_exit_char.		**
 ** Output Parms:	size_t *const ptr_szt_idx_chars.	**
 ** Result:		Function 'gets' that returns a string of**
 **			characters, whose characters are in a	**
 **			contiguous region of memory defined by	**
 **			the user.				**
 **			They occupy or use local scope work	**
 **			variables within the function.		**
 ****************************************************************/
char *gets(size_t *const ptr_szt_idx_chars, const size_t szt_num_chars, const char chr_exit_char)
	{
		char chr_OneCharGetty = NULL_CHARACTER;
		char *ptr_chr_String_New = NULL;
		size_t szt_idx_chars = V_ZERO;

		if (ptr_chr_String_New = (char *) malloc((szt_num_chars + V_ONE) * sizeof(char)))
			{
				while ( ((chr_OneCharGetty = getchar()) != chr_exit_char) && (szt_idx_chars < szt_num_chars) )
					ptr_chr_String_New[szt_idx_chars++] = chr_OneCharGetty;

				*(ptr_chr_String_New + szt_idx_chars) = NULL_CHARACTER;
			}
		else
			printf("Insufficient memory space to accommodate the character pointer...\n");

		if (ptr_szt_idx_chars) *ptr_szt_idx_chars = szt_idx_chars;
		return (ptr_chr_String_New);
	}

/*****************************************************************
 ** Function:		main.					**
 ** Explanation:	In this main function, what is sought is**
 **			for the user to enter by keyboard the	**
 **			number of characters that the memory	**
 **			area where the string will be stored	**
 **			will have, and subsequently, the user is**
 **			asked to enter each character that will	**
 **			be stored until finishing with car	**
 **			return.					**
 ** Input Parms:	None.					**
 ** Output Parms:	None.					**
 ** Result:		The function returns as a result the	**
 **			information generated by the memory	**
 **			allocation to the string.		**
 **			Such information is its maximum length,	**
 **			its effective size, its memory address,	**
 **			its content and the delimiter used for	**
 **			this purpose.				**
*****************************************************************/
int main()
	{
		/* Initial declaration of work variables. */
		char *ptr_chr_String_New = NULL;
		size_t szt_idx_chars = V_ZERO;
		size_t szt_num_chars = V_ZERO;

		/* Information entry window. */
		printf("+===|====+===|====+===|====+===|====+===|\n");
		printf("+  Generator of a character string.     +\n");
		printf("+===|====+===|====+===|====+===|====+===|\n");
		printf("String length : ");
		scanf("%ld%*c", &szt_num_chars);

		/* The character string is captured, character by character, into a dynamic buffer. */
		printf("Text string   : ");
		ptr_chr_String_New = gets(&szt_idx_chars, szt_num_chars, CARRIAGE_RETURN);

		/* Obtaining the exact number of characters with which the string will be created. */
		printf("\n");
		printf("+===|====+===|====+===|====+===|====+===|\n");
		printf("| General information about the string. |\n");
		printf("+===|====+===|====+===|====+===|====+===|\n");
		printf("|       Target output variables.        |\n");
		printf("+---|----+---|----+---|----+---|----+---|\n");
		printf("| Lenght  : [%p] = [%ld].\n", &szt_idx_chars, szt_idx_chars);
		printf("| Maximum : [%p] = [%ld].\n", &szt_num_chars, szt_num_chars);
		printf("+---|----+---|----+---|----+---|----+---|\n");
		printf("|     Target mapping string pointer.    |\n");
		printf("+---|----+---|----+---|----+---|----+---|\n");
		printf("| Address : [%p].\n", &ptr_chr_String_New);
		printf("| Pointer : [%p].\n", ptr_chr_String_New);
		printf("| Content : [%s].\n", ptr_chr_String_New);
		printf("+---|----+---|----+---|----+---|----+---|\n");
		printf("+Dump the string character by character.+\n");
		printf("+---|----+---|----+---|----+---|----+---|\n");

		/* Character-by-character dump of the created character string. */
		for (size_t szt_idx_char = V_ZERO; szt_idx_char < szt_idx_chars; szt_idx_char++)
			printf("#[%ld]\t:\t[%p]\t=\t[%c].\n", szt_idx_char, ptr_chr_String_New + szt_idx_char, *(ptr_chr_String_New + szt_idx_char));

		printf("[%ld] Obtained output results.\n", szt_idx_chars);

		/* Free memory area that stores the pointer to the created character string. */
		free(ptr_chr_String_New);

		return (V_ZERO);
	}
